name: apollo

channels:
    - conda-forge
    - pytorch
    - defaults

dependencies:
    # Core stack
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - cartopy
    - pandas
    - dask
    - dask-ml
    - xarray>=0.10
    - netcdf4
    - pynio
    - scikit-learn
    - xgboost
    - pytorch
    - requests

    # Documentation
    - sphinx
    - sphinx_rtd_theme

    # Dev tooling
    - ipython
